-- 프로필 · 리더보드 · 플래그. 시체 테이블은 0002_corpses.sql에서 따로 만든다.

CREATE TABLE IF NOT EXISTS profiles (
  token TEXT PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  season TEXT NOT NULL DEFAULT '',
  upgrades TEXT NOT NULL DEFAULT '{}',
  bank INTEGER NOT NULL DEFAULT 0,
  season_cats INTEGER NOT NULL DEFAULT 0,
  best_depth INTEGER NOT NULL DEFAULT 0,
  best_cats INTEGER NOT NULL DEFAULT 0,
  clinic_uses INTEGER NOT NULL DEFAULT 0,
  tutorial_done INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  token TEXT NOT NULL,
  name TEXT NOT NULL,
  season TEXT NOT NULL,
  depth REAL NOT NULL,
  cats INTEGER NOT NULL,
  at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_runs_season ON runs(season);
CREATE INDEX IF NOT EXISTS idx_runs_token ON runs(token);

CREATE TABLE IF NOT EXISTS flags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  x REAL NOT NULL,
  y REAL NOT NULL,
  msg TEXT NOT NULL,
  level INTEGER NOT NULL,
  owner TEXT NOT NULL,
  season TEXT NOT NULL,
  at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_flags_season ON flags(season);
